<style type="text/css">

ul.sortable li {
	padding-left: 20px;
	margin-bottom: 1px;
	cursor: move;
	background: url(<?php echo $this->getSkinUrl() ?>images/fam_leaf.png) no-repeat;
}

</style>
<table cellspacing="0" class="actions">
	<tr>
		<td class="filter-actions a-right">
			<button class="scalable back" onclick="Windows.closeAll()" type="button"><span>Back</span></button>
			<button class="scalable save" onclick="saveSortOrder('<?php echo $this->getAttributeId() ?>')" type="button"><span>Save</span></button>
		</td>
	</tr>
	<tr>
		<td>
			<?php $collection = $this->getCollection() ?>
			<?php if(count($collection)): ?>
				<ul id="collection_items" class="sortable">
					<?php foreach($collection as $template): ?>
						<li id="<?php echo $template->getId() ?>"><?php echo $template->getName() ?></li>
					<?php endforeach ?>
				</ul>
			<?php endif; ?>
		</td>
	</tr>
</table>
<script type="text/javascript">
	Sortable.create("collection_items", { scroll:true });
</script>
