<?php
/**
 * Delorum Framework
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://framework.delorum.com/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@delorum.com so we can send you a copy immediately.
 *
 * @category   Delorum
 * @package    Delorum
 * @copyright  Copyright (c) 2009 Delorum Inc. (http://www.delorum.com)
 * @license    http://framework.delorum.com/license/new-bsd     New BSD License
 * @version    1.0
 */
 
?>
<input type="hidden" name="<?php echo $this->getName() ?>" id="<?php echo $this->getHtmlId() ?>" value="<?php echo $this->getValue() ?>" />
<button type="button" onclick="openModal('<?php echo $this->getModalUrl() ?>', '1000', '300', true)">Click to Assign</button>
<a href="#" onclick="orderInstanceCollection('<?php echo $this->getSortModalUrl() ?>', '<?php echo $this->getHtmlId() ?>', '<?php echo $this->getId() ?>'); return false;">Sort Order</a>