<?php
/**
 * Delorum Framework
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://framework.delorum.com/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@delorum.com so we can send you a copy immediately.
 *
 * @category   Delorum
 * @package    Delorum
 * @copyright  Copyright (c) 2009 Delorum Inc. (http://www.delorum.com)
 * @license    http://framework.delorum.com/license/new-bsd     New BSD License
 * @version    1.0
 */
 
?>
<select id="<?php echo $this->getHtmlId() ?>" name="<?php echo $this->getName() ?>">
	<?php foreach($this->getTagsCollection() as $tag): ?>
		<option value="<?php echo $tag['value'] ?>" <?php if($this->getValue() == $tag['value']): ?>selected="selected"<?php endif; ?>><?php echo $tag['label'] ?></option>
	<?php endforeach; ?>
</select>
<a href="#" onclick="orderTagCollection('<?php echo $this->getSortModalUrl() ?>', '<?php echo $this->getHtmlId() ?>', '<?php echo $this->getId() ?>'); return false;">Sort Order</a>