<style type="text/css">
#left-photo 			{margin-left: 15px; float: left; width: 375px; border-right: 1px solid #CCCCCC;}
#right-photo 			{float: left; width: 375px; padding-left: 25px;}
.image-label			{float: left; width: 60px;}
#new-tags				{padding: 10px 0px 10px 0px; width: 100%; border-top: 1px solid #CCCCCC;}
.photo-header			{color: #EB5E00;}
#tags-input				{color: #CCCCCC;}
.tag-checkbox			{margin-right: 8px;}
#border-bottom 			{float: left; margin-left: 15px; border-top: 1px solid #CCCCCC; width: 100%; height: 1px;}
.current-tags			{padding: 2px 0px 2px 0px;}
.current-tags a			{text-decoration: none; color: #000000;}
.current-tags:hover 	{background-color: red; color: #ffffff; cursor: pointer;}
.current-tags:hover a 	{color: #ffffff;}
.delete-box				{float:right; width:15px; height: 15px; background-image: url(<?php echo Mage::getBaseUrl('web') ?>skin/adminhtml/default/default/images/x_close.gif);}
</style>
<!-- left div -->
<div id="left-photo">
	<img src="<?php echo $this->getPhotoUrl() ?>" /><br />
	
	<div class="image-label">File</div>
	<input type="file" style="width:40px;" id="image" name="image"><br />
	
	<div class="image-label">Rank</div>
	<input type="text" id="rank" size="10" name="rank" value="<?php echo $this->getRank() ?>"><br /><br />
	
	<h3 class="photo-header">New Tag</h3>
	<div id="new-tags">
		<input type="text" id="tags-input" name="newtags" size="35" value="Write custom tags here" />
		<br /><br />
		Popular Tags:
		<br /><br />
		<table>
		<?php $x = 0 ?>
		<?php foreach($this->staticTags() as $tag): ?>
			<?php if(!$x%2): ?>
				<tr>
			<?php endif ?>
			<td><input type="checkbox" class="tag-checkbox" name="populartags[]" value="<?php echo $tag->getTagId() ?>"><?php echo $tag->getName() ?></td>
			<?php if($x % 2): ?>
				</tr>
			<?php endif ?>
			<?php $x++; ?>
		<?php endforeach ?>

		<?php $x = 1 ?>
		<?php foreach($this->popularTags() as $tag): ?>
			<?php if(!$x%2): ?>
				<tr>
			<?php endif ?>
			<td><input type="checkbox" class="tag-checkbox" name="populartags[]" value="<?php echo $tag->getTagId() ?>"><?php echo $tag->getTagName() ?></td>
			<?php if($x % 2): ?>
				</tr>
			<?php endif ?>
			<?php $x++; ?>
		<?php endforeach ?>
		</table>
	</div>
</div>

<!-- right div -->
<div id="right-photo">
<h3 class="photo-header">Current Tags</h3>
	<table>
	<?php $x = 0 ?>
	<?php foreach($this->getPhotoTags() as $tag): ?>
		<?php if(!$x%2): ?>
				<tr>
		<?php endif ?>
			<td class="current-tags" id="<?php echo $tag->getTagId() ?>"><?php echo $tag->getName() ?><a onclick="removeTag(<?php echo $tag->getTagId() ?>, <?php echo $this->getRequest()->getParam('id') ?>);" href="javascript:void(0);"><div class="delete-box"></div></a></td>
		<?php if($x % 2): ?>
				</tr>
		<?php endif ?>
		<?php $x++; ?>
	<?php endforeach ?>
	</table>
</div>

<div id="border-bottom"></div>

<script type="text/javascript">
Event.observe('tags-input', 'focus', function(event) {
    if($('tags-input').value == 'Write custom tags here') {
    	$('tags-input').value = '';
    	$('tags-input').setStyle({
    		color: '#000000'
    	});
    }
});
function removeTag(lid, id)
{
	new Ajax.Request(<?php echo "'" . Mage::getModel('adminhtml/url')->getUrl('stock/adminhtml_photo/deleteTag', array() ) . "'"; ?>, {
	    method: 'get',
	    parameters: { tag_id: lid, pid: id, form_key: FORM_KEY },
	    onSuccess: function(transport)
	    {
	    	window.location.reload()
	    }
	});
}
</script> 