defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: kiel-photo

test:
  <<: *defaults
  database: eric_kiel_photo_test

# set these environment variables on your prod server
production:
  database: kiel-photo
#  uri: <%= ENV['MONGOHQ_URL'] %>