development:
  bucket: bentobox2
  bucket_mid: bentobox2
  bucket_small: bentobox2
  bucket_thumb: bentobox2
  access_key_id: AKIAIGD4BGCJYJ4KSKLQ
  secret_access_key: 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
test:
  bucket: bucket-test
  access_key_id: xxx
  secret_access_key: xxx
production:
  bucket: kiel
  bucket_mid: kiel_mid
  bucket_small: kiel_small
  bucket_thumb: kiel_thumb
  access_key_id: AKIAJFVAOJAM4DL7MI5Q
  secret_access_key: 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
