<?php
/**
 * Delorum Framework
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://framework.delorum.com/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@delorum.com so we can send you a copy immediately.
 *
 * @category   Delorum
 * @package    Delorum
 * @copyright  Copyright (c) 2009 Delorum Inc. (http://www.delorum.com)
 * @license    http://framework.delorum.com/license/new-bsd     New BSD License
 * @version    1.0
 */
 
?>
<style type="text/css">
	body {padding: 0px; margin: 0px;}
</style>
<script type="text/javascript">
<?php if($file = $this->getUploadedFile()): ?>
	parent.$('<?php echo $this->getId() ?>').value = '<?php echo $file ?>';
	parent.$('<?php echo $this->getName() ?>_preview').src = '<?php echo Mage::getBaseUrl('media') . 'template' . $file ?>';
	parent.Element.hide('loading-mask');
	
<?php endif; ?>
function upload(){
	parent.Element.show('loading-mask');
	document.getElementById('submitter').submit();
}
</script>

<form id="submitter" action="<?php echo Mage::getModel('adminhtml/url')->getUrl('vladmin/adminhtml_template_media/saveImage'); ?>" method="post" enctype="multipart/form-data">
	<input type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" name="form_key"/>
	<input type="hidden" name="name" value="<?php echo $this->getName() ?>" />
	<input type="hidden" name="id" value="<?php echo $this->getId() ?>" />
	<input id="file" type="file" name="image" onChange="upload()" size="10"/><br>
</form>